# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RC_RxKeyboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RC_RxKeyboard
pod 'RxSwift'
pod 'RxDataSources'
pod 'RxCocoa'
pod 'NSObject+Rx'
pod 'RxKeyboard'
pod 'Action'
end
