# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RC_RxFlow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RC_RxFlow
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'
pod 'NSObject+Rx'
pod 'RxFlow'
pod 'SDWebImage'
end
